version: "3"

services:
  slurmctl:
    build: .
    image: drew-docker-centos7-slurm:latest
    hostname: slurmctl
    stdin_open: true
    tty: true
    ports:
      - "6819:6819"
      - "6820:6820"
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - slurmctl-lib-volume:/var/lib/slurmd
      - slurmctl-spool-volume:/var/spool/slurm
      - slurmctl-log-volume:/var/log/slurm
      - slurmctl-db-volume:/var/lib/mysql
      - slurmctl-jwt-volume:/etc/slurm/jwt
      - slurm-workdir-volume:/home/slurmrestd/shared
    environment:
      NODE_TYPE: controller
      SLURM_JWT_KEY:
  slurmd:
    build: .
    image: drew-docker-centos7-slurm:latest
    hostname: slurmd
    stdin_open: true
    tty: true
    ports:
      - "6818:6818"
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - slurmd-lib-volume:/var/lib/slurmd
      - slurmd-spool-volume:/var/spool/slurm
      - slurmd-log-volume:/var/log/slurm
      - slurmd-db-volume:/var/lib/mysql
      - slurmd-jwt-volume:/etc/slurm/jwt
      - slurm-workdir-volume:/home/slurmrestd/shared
    environment:
      NODE_TYPE: worker
      SLURM_JWT_KEY:
volumes:
  slurmctl-db-volume:
  slurmctl-log-volume:
  slurmctl-spool-volume:
  slurmctl-lib-volume:
  slurmctl-jwt-volume:
  slurmd-db-volume:
  slurmd-log-volume:
  slurmd-spool-volume:
  slurmd-lib-volume:
  slurmd-jwt-volume:
  slurm-workdir-volume:
